server:
  port: 8866
spring:
  datasource:
    url: jdbc:mysql://89.208.254.83:3307/carnival?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: carnival
    password: '7LkjMzRdhMh^yAhc'
  redis:
    host: 89.208.254.83
    port: 6379
    database: 0
    password: 123456