server:
  port: 9998
spring:
  datasource:
    url: jdbc:mysql://192.168.50.100:3307/carnival?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: carnival
    password: '7LkjMzRdhMh^yAhc'
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0